version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
    working_directory: /work
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: make SUDO="" setup
      - run: make test
      - run: make
      - persist_to_workspace:
          root: /work/bin
          paths:
            - contour-plus
  docker:
    docker:
      - image: docker:stable
    steps:
      - run:
          name: Install tools
          command: |
            apk add --no-cache git
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy binary
          command: |
            mkdir -p bin
            cp /tmp/workspace/contour-plus bin
            chmod a+x bin/contour-plus
      - run: docker build -t quay.io/cybozu/contour-plus:latest .
      - run:
          name: Push image to quay.io
          command: |
            if [ "$CIRCLE_TAG" = "" ]; then exit 0; fi
            docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
            echo "pushing image ..."
            TAG=$(echo $CIRCLE_TAG | cut -c 2-)
            docker tag quay.io/cybozu/contour-plus:latest quay.io/cybozu/contour-plus:$TAG
            docker push quay.io/cybozu/contour-plus:$TAG
            if echo $TAG | grep -q -e - ; then
                echo ===== Skip pushing branch tags for pre-release $TAG =====
                exit 0
            fi
            docker push quay.io/cybozu/contour-plus:latest

workflows:
  version: 2
  main:
    jobs:
      - build
      - docker:
          requires:
            - build
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - docker:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
