apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contour-plus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contour-plus
subjects:
- kind: ServiceAccount
  name: contour
