name: Main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build-binary:
    name: build binary
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build binary
        run: |
          make SUDO="" setup
          make test
          make
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: bin/contour-plus
          retention-days: 1

  build-image:
    name: build image
    needs: build-binary
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: binary
      - name: Copy binary
        run: |
          mkdir -p bin
          cp contour-plus bin/
          chmod a+x bin/contour-plus
      - name: Build image
        run: |
          docker build -t quay.io/cybozu/contour-plus:latest .
          docker save -o contour-plus.img quay.io/cybozu/contour-plus:latest
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: contour-plus.img
          retention-days: 1

  push-image:
    name: push image
    needs: build-image
    if: startsWith( github.ref, 'refs/tags/v' )
    runs-on: ubuntu-20.04
    steps:
      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image
      - name: Push image to quay.io
        run: |
          docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
          echo "pushing ${TAG} ..."
          TAG=${GITHUB_REF#refs/tags/}
          docker load -i contour-plus.img
          docker tag quay.io/cybozu/contour-plus:latest quay.io/cybozu/contour-plus:$TAG
          docker push quay.io/cybozu/contour-plus:$TAG
          if echo $TAG | grep -q -e - ; then
              echo ===== Skip pushing branch tags for pre-release $TAG =====
              exit 0
          fi
          docker push quay.io/cybozu/contour-plus:latest


