name: daily-sync
on:
  schedule:
    - cron: '0 10 * * *'
jobs:
  sync:
    name: Sync main with upstream
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Sync main
        run: |
          git remote add upstream https://github.com/cybozu-go/contour-plus.git
          git fetch upstream main
          git rebase upstream/main
          git push origin main --force
      - name: Sync tag
        run: |
          ORIGIN_TAG="$(git ls-remote --tags origin | grep -oP 'refs/tags/v\d+\.\d+\.\d+' | tail -n1 | awk -F / '{print $NF}')"
          UPSTREAM_TAG="$(git ls-remote --tags upstream | grep -oP 'refs/tags/v\d+\.\d+\.\d+' | tail -n1 | awk -F / '{print $NF}')"
          if [ "${ORIGIN_TAG}" = "${UPSTREAM_TAG}" ]; then exit 0; fi
          UPSTREAM_COMMIT="$(git ls-remote --tags upstream | grep ${UPSTREAM_TAG} | awk '{print $1}')"
          git checkout ${UPSTREAM_COMMIT}
          git rebase origin/master
          git tag ${UPSTREAM_TAG}
          git push origin ${UPSTREAM_TAG} || true
